// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: public/messages.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FromServer_SType int32

const (
	FromServer_Hello FromServer_SType = 0
)

// Enum value maps for FromServer_SType.
var (
	FromServer_SType_name = map[int32]string{
		0: "Hello",
	}
	FromServer_SType_value = map[string]int32{
		"Hello": 0,
	}
)

func (x FromServer_SType) Enum() *FromServer_SType {
	p := new(FromServer_SType)
	*p = x
	return p
}

func (x FromServer_SType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FromServer_SType) Descriptor() protoreflect.EnumDescriptor {
	return file_public_messages_proto_enumTypes[0].Descriptor()
}

func (FromServer_SType) Type() protoreflect.EnumType {
	return &file_public_messages_proto_enumTypes[0]
}

func (x FromServer_SType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FromServer_SType.Descriptor instead.
func (FromServer_SType) EnumDescriptor() ([]byte, []int) {
	return file_public_messages_proto_rawDescGZIP(), []int{0, 0}
}

type FromClient_CType int32

const (
	FromClient_Hello FromClient_CType = 0
)

// Enum value maps for FromClient_CType.
var (
	FromClient_CType_name = map[int32]string{
		0: "Hello",
	}
	FromClient_CType_value = map[string]int32{
		"Hello": 0,
	}
)

func (x FromClient_CType) Enum() *FromClient_CType {
	p := new(FromClient_CType)
	*p = x
	return p
}

func (x FromClient_CType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FromClient_CType) Descriptor() protoreflect.EnumDescriptor {
	return file_public_messages_proto_enumTypes[1].Descriptor()
}

func (FromClient_CType) Type() protoreflect.EnumType {
	return &file_public_messages_proto_enumTypes[1]
}

func (x FromClient_CType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FromClient_CType.Descriptor instead.
func (FromClient_CType) EnumDescriptor() ([]byte, []int) {
	return file_public_messages_proto_rawDescGZIP(), []int{2, 0}
}

type FromServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  FromServer_SType `protobuf:"varint,1,opt,name=type,proto3,enum=rts.FromServer_SType" json:"type,omitempty"`
	Hello *Hello           `protobuf:"bytes,2,opt,name=hello,proto3" json:"hello,omitempty"`
}

func (x *FromServer) Reset() {
	*x = FromServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FromServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromServer) ProtoMessage() {}

func (x *FromServer) ProtoReflect() protoreflect.Message {
	mi := &file_public_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromServer.ProtoReflect.Descriptor instead.
func (*FromServer) Descriptor() ([]byte, []int) {
	return file_public_messages_proto_rawDescGZIP(), []int{0}
}

func (x *FromServer) GetType() FromServer_SType {
	if x != nil {
		return x.Type
	}
	return FromServer_Hello
}

func (x *FromServer) GetHello() *Hello {
	if x != nil {
		return x.Hello
	}
	return nil
}

type Hello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Greeting string `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
}

func (x *Hello) Reset() {
	*x = Hello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_public_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_public_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

type FromClient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type FromClient_CType `protobuf:"varint,1,opt,name=type,proto3,enum=rts.FromClient_CType" json:"type,omitempty"`
}

func (x *FromClient) Reset() {
	*x = FromClient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FromClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromClient) ProtoMessage() {}

func (x *FromClient) ProtoReflect() protoreflect.Message {
	mi := &file_public_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromClient.ProtoReflect.Descriptor instead.
func (*FromClient) Descriptor() ([]byte, []int) {
	return file_public_messages_proto_rawDescGZIP(), []int{2}
}

func (x *FromClient) GetType() FromClient_CType {
	if x != nil {
		return x.Type
	}
	return FromClient_Hello
}

var File_public_messages_proto protoreflect.FileDescriptor

var file_public_messages_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x74, 0x73, 0x22, 0x6d, 0x0a, 0x0a,
	0x46, 0x72, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x29, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x72, 0x74, 0x73, 0x2e, 0x46,
	0x72, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x72, 0x74, 0x73, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x52, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x22, 0x12, 0x0a, 0x05, 0x53, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x09, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x10, 0x00, 0x22, 0x23, 0x0a, 0x05, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67,
	0x22, 0x4b, 0x0a, 0x0a, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x29,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x72,
	0x74, 0x73, 0x2e, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x12, 0x0a, 0x05, 0x43, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x10, 0x00, 0x42, 0x0b, 0x5a,
	0x09, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_public_messages_proto_rawDescOnce sync.Once
	file_public_messages_proto_rawDescData = file_public_messages_proto_rawDesc
)

func file_public_messages_proto_rawDescGZIP() []byte {
	file_public_messages_proto_rawDescOnce.Do(func() {
		file_public_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_public_messages_proto_rawDescData)
	})
	return file_public_messages_proto_rawDescData
}

var file_public_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_public_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_public_messages_proto_goTypes = []interface{}{
	(FromServer_SType)(0), // 0: rts.FromServer.SType
	(FromClient_CType)(0), // 1: rts.FromClient.CType
	(*FromServer)(nil),    // 2: rts.FromServer
	(*Hello)(nil),         // 3: rts.Hello
	(*FromClient)(nil),    // 4: rts.FromClient
}
var file_public_messages_proto_depIdxs = []int32{
	0, // 0: rts.FromServer.type:type_name -> rts.FromServer.SType
	3, // 1: rts.FromServer.hello:type_name -> rts.Hello
	1, // 2: rts.FromClient.type:type_name -> rts.FromClient.CType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_public_messages_proto_init() }
func file_public_messages_proto_init() {
	if File_public_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_public_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FromServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_public_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_public_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FromClient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_public_messages_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_public_messages_proto_goTypes,
		DependencyIndexes: file_public_messages_proto_depIdxs,
		EnumInfos:         file_public_messages_proto_enumTypes,
		MessageInfos:      file_public_messages_proto_msgTypes,
	}.Build()
	File_public_messages_proto = out.File
	file_public_messages_proto_rawDesc = nil
	file_public_messages_proto_goTypes = nil
	file_public_messages_proto_depIdxs = nil
}
